version: "3.8"

services:
  database:
    ports:
      - '5432:5432'
    volumes:
      - './volumes/postgresql/:/bitnami/postgresql'
    environment:
      - POSTGRES_PASSWORD=Zv2kEX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
  backend:
    env_file:
      - ./backend/.env.dev
    ports:
      - 5000:5000

