version: "3.8"

services:
  database:
    ports:
      - '5432:5432'
    volumes:
      - scraper-db:/bitnami/postgresql
    environment:
      - POSTGRES_PASSWORD=Zv2kEX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
      - TZ=Asia/Ho_Chi_Minh
  backend:
    image: 21jake/scraper-backend
    env_file:
      - ./backend/.env.dev
    ports:
      - 5000:5000
    volumes:
      - './volumes/backend-storage/csv:/backend/storage/csv'
      - './volumes/backend-storage/html:/backend/storage/html'

volumes:
  scraper-db:
    name: scraper-db