version: "3.8"

services:
  database:
    ports:
      - '5432:5432'
    volumes:
      - scraper-db:/bitnami/postgresql
    environment:
      - POSTGRES_PASSWORD=Zv2kEX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev
      - TZ=Asia/Ho_Chi_Minh
      - POSTGRESQL_TIMEZONE=Asia/Ho_Chi_Minh
  backend:
    image: jake21/scraper-backend
    env_file:
      - ./backend/.env.dev
    ports:
      - 5000:5000
    volumes:
      - './volumes/backend-storage:/app/storage'
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
  frontend:
    image: jake21/scraper-frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev

volumes:
  scraper-db:
    name: scraper-db