version: "3.8"

services:
  database:
    image: docker.io/bitnami/postgresql:15
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  backend:
    image: jake21/scraper-backend
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
  frontend:
    image: jake21/scraper-frontend
    platform: linux/amd64
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3001:80"